### ISSUE TITLE
better example for setting stuff

### ISSUE THREAD

**Issue by luxus** [kkckkc/ZWayMqttEndpoint#2]
in mqtt i see this
![bildschirmfoto 2016-05-15 um 18 59 55](https://cloud.githubusercontent.com/assets/7449/15275551/4576a978-1acf-11e6-824e-765a87d57c37.png)

whats the right way to update the level?
i tried this
topic: `zwaymqtt/devices/zwayvdev_zway_8_0_67_1/set` 
```json
{"id":"ZWayVDev_zway_8-0-67-1","title":"Zieltemperatur","icon":"thermostat","type":"thermostat","level":20}
```
but nothing happens in z-way

oh i got this error in the log window 
```19:05 | Error during perform command execution: TypeError: Cannot read property 'level' of undefined```

**Comment by kkckkc** [comment]
I don't have any z-wave dimmers, but for a switch you should in your example send 

`{ "command":"on" }` 

to topic `zwaymqtt/devices/zwayvdev_zway_8_0_67_1/set`

The general format is 

`{ "command":"<command>", "args": <args> }`

This calls `performCommand` as documented at http://razberry.z-wave.me/docs/zwayDev.pdf

My guess is that the following payload would work with a dimmer

`{ "command":"exact", "args": 45 }`

**Comment by kkckkc** [comment]
Correction, the payload should probably be

{ "command":"exact", "args": { "level": 45 } }

**Comment by luxus** [comment]
perfect.. it works with
```{ "command": "exact", "args": { "level": 20 } }```
